### ISSUE TITLE
Total ripoff of cgminer

### ISSUE THREAD

**Issue by davidcroda** [luke-jr/bfgminer#192]
Why is no credit given in readme? Why did you copy the documentation exactly and find/replace your name.

**Comment by luke-jr** [comment]
cgminer is just as much a "ripoff" of BFGMiner - actually more, since Con actually claimed credit for the FPGA code which cgminer took from BFGMiner (cgminer's original code was CPU and GPU only; FPGA came from BFGMiner). In any case, BFGMiner properly attributes all the major authors in the AUTHORS file and the copyrights on the relevant files.
