### ISSUE TITLE
Please merge branch gridseed into master

### ISSUE THREAD

**Issue by TryMyVeryBest** [luke-jr/bfgminer#427]
Hello and thanks for your brilliant work,
I'm just a user and deserving the complete support for gridseed-based devices like dualminer (merged) and the 5-chip-usb-devices. Handling with cgminer or cpuminer just stole my last nerves so I claim your fantastic abilities :)

**Comment by tonyrayo** [comment]
Gridseed support is planned for BFGMiner 4.0 (although I don't know if there is an ETA on that release).  I'm not sure which platform you are using, but if it is Windows, you can use the miner found here - http://cryptomining-blog.com/1396-download-bfgminer-3-10-0-for-windows-scrypt-mining-on-gridseed-5-chip-asics/ - the same site has advice on how to compile it for other situations (Mac OSX, Linux, Debian/RPi).

**Comment by TryMyVeryBest** [comment]
Thanks for that hint but I am not able to find any advice for compiling for Linux on that website. Hope for an update and looking forward to bfgminer 4.0

**Comment by tonyrayo** [comment]
Gridseed/DualMiner support actually works if you pull/build the latest bfgminer, however there are some alternate versions.  http://www.reddit.com/r/litecoinmining/comments/20qddx/a_simple_guild_to_set_up_gridseed_ltc_mining_rig/ <= mostly for Windows and Rasperian but Rasperian and Debian/other Linux platforms are enough alike that those directions should work well.  Since a lot of people are just scrypt mining (really not cost effective for SHA256 or dual-mining, they have adopted RPi as it only adds another 5w, such as shown here - http://highoncoins.com/litecoin-rig/how-to-make-stackable-tower-gridseed-rig-with-raspberry-pi-pre-built-cgminer/ - although as the title says, it uses cgminer... actually both do).  If you are intent on using bfgminer over cgminer and don't want to/aren't able to compile from source, here are more RPi/Linux directions - https://bitcointalk.org/index.php?topic=517451.0

**Comment by gperez2000** [comment]
What about Gridseeds in BTC mode, Does BFGMiner support it..
