### ISSUE TITLE
Bfgminer 4.8.0 No longer detecting my R-Box

### ISSUE THREAD

**Issue by ManaMush** [luke-jr/bfgminer#553]
I had my R-Box and a gridseed going in 4.7.0 (Using Multiminter GUI). Upgraded to 4.8.0 last night, no issues. Got two new gridseeds and used the auto detect feature. It detected the new gridseeds but my R-Box is no longer detected. Windows does detect the R-box (Silicon Labs CP210x USB to UART Bridge controller)

**Comment by ManaMush** [comment]
Using 4.7.1 in the command line while using 4.8.0 for my gridseeds to mine litecoin. 4.7.1 is hashing much slower then it was when multiminer was using bfgminer 4.7.0 (averaging 26gh rather then the 33gh I was averaging). Ultimately I'd like to see a fix of the latest version so multiminer can detect my rockimner and get my hash rates up again.

**Comment by lextad** [comment]
I have a similar problem to. What  i have done was 
uninstall all drivers (reboot the pc)
unplug all miners
deleted bfgminer from the miners folder   C:\Users\????\AppData\Local\MultiMiner
plug one miner only 
install / check the correct driver was install 
open MM (will download the BFGminer)
run a scan hardware

**Comment by nwoolls** [comment]
Device detection was broken (specifically the Cointerra driver) in the official 4.8 release. What you need to do (if you are using MultiMiner) is delete the MultiMiner\Miners\BFGMiner folder and let MultiMiner re-download 4.7 (or build a new version of BFGMiner from Git).

This was fixed in 2d19cdb6fb9261bc725a2997057229b6344b0f3b
