### ISSUE TITLE
Slow miners declared SICK

### ISSUE THREAD

**Issue by luke-jr** [luke-jr/bfgminer#9]
...even when they're not

**Comment by luke-jr** [comment]
Worked around in 7ebda09f7eebca3caab6f676ce630b6c56837fa1 for CPUs

**Comment by luke-jr** [comment]
Fixed in cab9bdc

**Comment by leder11011** [comment]
Can you please reconsider GPU mining declared SICK, as CPUs cannot get sick and as my hashrate is below 3 Mh/s.

**Comment by luke-jr** [comment]
That question does not make sense.

**Comment by leder11011** [comment]
I just have lots of SICK stoppings of bfgminer and always have to restart bfgminer. In an earlier version of cgminer that used to do scrypt/GPU mining, there were no such issues. As you wrote here and in the bug fix comments, the CPU cannot get sick, why can the GPU? And the fix is only for hashrates above 3 Mh/s, why is that?

**Comment by luke-jr** [comment]
It doesn't make sense for the CPU to get sick (if it did, BFGMiner itself would die!). Below 3 Mh/s, the device should never be considered SICK (for this reason; other reasons still apply...)
